set_operation:
  description: >
    Changes operation mode
  fields:
    real_mode:
      description: Mode to set to the Tesla gateway.
      example: "self_consumption, autonomous"
    backup_reserve_percent:
      description: Percentage of battery reserved for outages
      example: 10
set_reserve:
  description: >
    Changes battery reserve percent
  fields:
    backup_reserve_percent:
      description: Percentage of battery reserved for outages
      example: 70
set_tariff:
  description: >
    Sets the tariff details to be used in time based control mode
  fields:
    default_prices:
      description: The default prices in the format "<buy> <sell> <name>"
      example: "0.29 0.1 OFF_PEAK"
    tariff_periods:
      description: The prices for different time periods
      example: {"0.29 0.29 ON_PEAK": [ [18000, 36000], [57600, 75600] ]}
    provider:
      description: The name of your electricity provider
      example: "My electricity co"
set_import_export:
  description: >
    Changes the grid import and export settings
  fields:
    allow_grid_charging:
      description: Whether to allow charging the battery from the grid
      example: true
    allow_battery_export:
      description: Whether to allow exporting to the grid from the battery
      example: false